services:
  sc-gateway:
    restart: always
    container_name: sc-gateway
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROFILE_ACTIVE: test

      KC_REALM: realm
      KC_SERVER_URL: http://localhost:8181
      KC_CLIENT_ID: client-id
      KC_CLIENT_SECRET: client-secret

      ROOT_LOG_LEVEL: error
      WEB_LOG_LEVEL: debug

      EUREKA_APP_NAME: gateway
      DEFAULT_ZONE: http://admin:admin@localhost:8080/eureka/
      USER_SERVICE_ID: user-service
      PROJECT_SERVICE_ID: project-service
      CHAT_SERVICE_ID: chat-service
      FILE_SERVICE_ID: file-service
      POST_SERVICE_ID: post-service
    volumes:
      - logs:/app/logs
volumes:
  logs:
    name: gateway-logs