services:
  sc-gateway:
    image: nhatbangle/sc-gateway:latest
    restart: always
    container_name: sc-gateway
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROFILE_ACTIVE: prod
      ENABLE_SECURITY: true
      KC_SERVER_URL: localhost:8086
      KC_REALM: sc-realm
      KC_CLIENT_ID: sc-service
      KC_CLIENT_SECRET: secret
      USER_SERVICE_URL: localhost:8081
      PROJECT_SERVICE_URL: localhost:8082
      CHAT_SERVICE_URL: localhost:8083
      FILE_SERVICE_URL: localhost:8084
      POST_SERVICE_URL: localhost:8085
    volumes:
      - logs:/app/logs
volumes:
  logs:
    name: gateway-logs