spring:
  application:
    name: gateway
  security:
    user:
      name: ${SECURE_USER:user}
      password: ${SECURE_PASSWORD:user}
  profiles:
    active: dev

# Service IDs
PROJECT_SERVICE_INSTANCE_ID: ${PROJECT_SERVICE_ID:project-service}
CHAT_SERVICE_INSTANCE_ID: ${CHAT_SERVICE_ID:chat-service}
FILE_SERVICE_INSTANCE_ID: ${FILE_SERVICE_ID:file-service}
POST_SERVICE_INSTANCE_ID: ${POST_SERVICE_ID:post-service}

eureka:
  instance:
    appname: ${EUREKA_APP_NAME:unknown}
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://admin:admin@localhost:8080/eureka/}

logging:
  file:
    name: ./logs/sc-gateway.log
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:error}

# API docs - Swagger
springdoc:
  swagger-ui:
    path: /docs
    urls[0]:
      name: Project Service
      url: /aggregate/project/v3/api-docs
    urls[1]:
      name: Chat Service
      url: /aggregate/chat/v3/api-docs
    urls[2]:
      name: File Service
      url: /aggregate/file/v3/api-docs
    urls[3]:
      name: Post Service
      url: /aggregate/post/v3/api-docs
  api-docs:
    path: /api-docs
