server:
  port: 8081

spring:
  cloud:
    discovery:
      enabled: false

logging:
  level:
    org:
      keycloak: debug
      springframework:
        security: debug

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://admin:admin@localhost:8080/eureka/

keycloak:
  server-url: http://localhost:8181
  realm: realm
  client-id: client-id
  client-secret: client-secret

# Service IDs
USER_SERVICE_INSTANCE_ID: user-service
PROJECT_SERVICE_INSTANCE_ID: project-service
CHAT_SERVICE_INSTANCE_ID: chat-service
FILE_SERVICE_INSTANCE_ID: file-service
POST_SERVICE_INSTANCE_ID: post-service
